"""empty message

Revision ID: 53120d8ad4e2
Revises: 7d54b7fac7e8
Create Date: 2023-11-14 23:45:27.782218

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "53120d8ad4e2"
down_revision = "7d54b7fac7e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "base_character", sa.Column("character_location_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        None, "base_character", "character_location", ["character_location_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "base_character", type_="foreignkey")
    op.drop_column("base_character", "character_location_id")
    # ### end Alembic commands ###
