"""empty message

Revision ID: f31533b76516
Revises: 68f78752e1c5
Create Date: 2023-10-29 14:17:57.738370

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f31533b76516"
down_revision = "68f78752e1c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_attributes",
        sa.Column("base_character_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute.id"],
        ),
        sa.ForeignKeyConstraint(
            ["base_character_id"],
            ["base_character.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_attributes")
    # ### end Alembic commands ###
