"""empty message

Revision ID: 68f78752e1c5
Revises: e5089a8003d2
Create Date: 2023-10-29 14:12:10.482928

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68f78752e1c5"
down_revision = "e5089a8003d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ability",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("ability_type_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ability_type_id"],
            ["ability_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_ability",
        sa.Column("base_class_id", sa.UUID(), nullable=False),
        sa.Column("ability_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ability_id"],
            ["ability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["base_class_id"],
            ["base_class.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("class_ability")
    op.drop_table("ability")
    # ### end Alembic commands ###
